### ISSUE TITLE
Compare with other vars plugins

### ISSUE THREAD

**Issue by ai** [nathanhood/postcss-variables#2]
Great to see new variables plugin.

But users will be confused about current docs. Main question — what is difference with `postcss-simple-vars`. You need to write it more clear in first section.

**Comment by nathanhood** [comment]
Hey Andrey,

Thank you for taking the time to look at my repo!

There are a couple critical differences that I can explain in my README:

Simple vars allows you to pass default variables into the plugin. My repo does this as well, except that it also allows for this variables object (called ‘globals’ in my plugin) to be nested to handle a more complex set of default variables. These can be retrieved in your stylesheet with dot notation.
My plugin is compatible with a parser extension that I wrote for my company called postcss-wee-syntax (you and I actually emailed back and forth a few weeks back about this parser plugin). The main difference is that I added a custom ‘mixin’ type that is parsed into the AST structure. 
In addition to the ability to use dot notation for the globals/default variables object, my plugin also makes it possible to create a base variables file that can be extended by another variables file. This sounds arbitrary the way I am explaining it here, but it will give me the ability to support use in a framework where you would want to extend a set of default variables in a separate file without changing the framework’s source code. This is explained a little more at the bottom of the README.

If you have any suggestions for structuring or explaining these differences (or just any thoughts on the plugin itself), I would love to receive that feedback. Thanks!

Nathan

**Comment by ai** [comment]
Sure, just explain it in README.md. Users will be happy :).

**Comment by nathanhood** [comment]
Will do. Thanks!

Nathan's iPhone

**Comment by AndrewBogdanovTSS** [comment]
I personally find ‘globals’ amazing feature. Thanks for implementing it in such a way! 👍
